### ISSUE TITLE
'PRMSSoilzone' object has no attribute '_adjust_parameters'

### ISSUE THREAD

**Issue by markstro-usgs** [EC-USGS/pywatershed#249] opened 2023-10-31 17:51 UTC
I'm running my NHM CONUS input files through the latest pywatershed develop version.  I get the exception "AttributeError: 'PRMSSoilzone' object has no attribute '_adjust_parameters'" at pywatershed\hydrology\prms_soilzone.py:319 in _set_initial_conditions

I forgot to say that when I ran the much smaller Willamette model I didn't have this problem.

**Comment by jmccreight** [comment] 2023-10-31 21:57
Hi Markstrom,
This should not depend on the domain. And I'm not able to reproduce it (and
all the tests and notebooks passed before that was merged).
Can you try running notebook examples/02_... and let me know if that works?
I'm also not sure how youre installing pws, it could be related to that,
you might try uninstalling (pip uninstall -y pywatershed) and then
re-installing it (pip install -e .)





-------------------------------------------------------
James L. McCreight
Research Hydrologist ~ Software Engineer
USGS Enterprise Capacity
UCAR CPAESS
cell:         831-261-5149

**Closed** 2023-11-06 17:44 UTC
